const watches = [
    {
        id: 1,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690637527/C4/Rolex/Oyster-Perpetual-Day-Date-40_tfpm7a.png',
        productName: 'Oyster Perpetual Day-Date 40',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Male',
        size: 40,
        material: 'Gold',
        price: 50000,
        onDiscount: 'Yes',
        oldPrice: 64980,
    },
    {
        id: 2,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690642518/C4/Rolex/Oyster-Perpetual-Day-Date-36_k2aodu.png',
        productName: 'Oyster Perpetual Day-Date 36',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Male',
        size: 36,
        material: 'Stainless Steel',
        price: 24550,
        onDiscount: 'No',
        oldPrice: null,
    }, {
        id: 3,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690642708/C4/Rolex/Sky-Dweller_oobast.png',
        productName: 'Sky-Dweller',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Male',
        size: 42,
        material: 'Gold',
        price: 70000,
        onDiscount: 'Yes',
        oldPrice: 104980,
    }
    , {
        id: 4,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690643795/C4/Rolex/GMT-Master_II_fojalb.png',
        productName: 'GMT-Master II',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Male',
        size: 40,
        material: 'Stainless Steel',
        price: 15000,
        oldPrice: 24200,
        onDiscount: 'Yes',
    },
    {
        id: 5,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690643717/C4/Rolex/GMT-Master_II_Gold_y9lgsr.png',
        productName: 'GMT-Master II',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Male',
        size: 40,
        material: 'Gold',
        price: 24200,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 6,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690643898/C4/Rolex/Yacht-Master_37_d8kyal.png',
        productName: 'Yacht-Master 37',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Male',
        size: 37,
        material: 'Rose Gold',
        price: 44200,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 7,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690644215/C4/Rolex/Yacht-Master_42_svo69f.png',
        productName: 'Yacht-Master 42',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Male',
        size: 42,
        material: 'White Gold',
        price: 65100,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 8,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690644373/C4/Rolex/Perpetual_1908_rfyb3t.png',
        productName: 'Perpetual 1908',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Male',
        size: 39,
        material: 'White Gold',
        price: 40200,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 9,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690644750/C4/Rolex/Day-Date_40_zjsuc3.png',
        productName: 'Day-Date 40',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Male',
        size: 40,
        material: 'White Gold',
        price: 84200,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 10,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690644873/C4/Rolex/Submariner_Date_zklgrb.png',
        productName: 'Submariner Date',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Male',
        size: 41,
        material: 'White Gold',
        price: 89000,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 11,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690645000/C4/Rolex/Submariner_mxkruz.png',
        productName: 'Submariner',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Male',
        size: 41,
        material: 'Stainless Steel',
        price: 5900,
        onDiscount: 'Yes',
        oldPrice: 8900,
    },
    {
        id: 12,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690645142/C4/Rolex/Milgauss_oswjcw.png',
        productName: 'Milgauss',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Male',
        size: 40,
        material: 'Stainless Steel',
        price: 9000,
        onDiscount: 'No',
        oldPrice: 8900,
    },
    {
        id: 13,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690645254/C4/Rolex/Cosmograph_Daytona_eyjbr7.png',
        productName: 'Cosmograph Daytona',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Male',
        size: 40,
        material: 'Gold',
        price: 30000,
        onDiscount: 'Yes',
        oldPrice: 50000,
    },
    {
        id: 14,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690645474/C4/Rolex/Explorer_sj7okx.png',
        productName: 'Explorer',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Male',
        size: 36,
        material: 'Stainless Steel',
        price: 11000,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 15,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690645581/C4/Rolex/Explorer_II_iqu9yd.png',
        productName: 'Explorer II',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Male',
        size: 42,
        material: 'Stainless Steel',
        price: 11000,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 16,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690645683/C4/Rolex/Cellini_Moonphase_krhx6o.png',
        productName: 'Cellini Moonphase',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Male',
        size: 39,
        material: 'Rose Gold',
        price: 39000,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 17,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690645840/C4/Rolex/Lady-Datejust_lvmcbo.png',
        productName: 'Lady-Datejust',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Female',
        size: 28,
        material: 'Gold',
        price: 45510,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 18,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690645954/C4/Rolex/Lady-Datejust-28_nfwul1.png',
        productName: 'Lady-Datejust-28',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Female',
        size: 28,
        material: 'Stainless Steel',
        price: 18000,
        onDiscount: 'Yes',
        oldPrice: 19000,
    },
    {
        id: 19,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690646047/C4/Rolex/Lady-Datejust-30_sjdywc.png',
        productName: 'Lady-Datejust-30',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Female',
        size: 30,
        material: 'White Gold',
        price: 32000,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 20,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690646177/C4/Rolex/Lady-Datejust-26_ksbkhx.png',
        productName: 'Lady-Datejust-26',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Female',
        size: 26,
        material: 'Rose Gold',
        price: 20000,
        onDiscount: 'Yes',
        oldPrice: 22000,
    },
    {
        id: 20,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690646461/C4/Rolex/Lady-Datejust-31_pv2jfh.png',
        productName: 'Lady-Datejust-31',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Rolex',
        gender: 'Female',
        size: 31,
        material: 'Gold',
        price: 47000,
        onDiscount: 'No',
        oldPrice: null,
    },

    {
        id: 22,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690654312/C4/Patek/Calatrava_Pilot_Travel_Time_Chronograph_uapr1v.png',
        productName: 'Calatrava Pilot Travel Time Chronograph',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Patek Philippe',
        gender: 'Male',
        size: 42,
        material: 'White Gold',
        price: 147000,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 23,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690654465/C4/Patek/Complications_Flyback_Chronograph_Annual_Calendar_jsem6t.png',
        productName: 'Complications Flyback Chronograph, Annual Calendar',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Patek Philippe',
        gender: 'Male',
        size: 42,
        material: 'Rose Gold',
        price: 1654000,
        onDiscount: 'Yes',
        oldPrice: 1700000,
    },
    {
        id: 24,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690654614/C4/Patek/Grand_Complications_MInute_Repeater_World_Time_hoyxpn.png',
        productName: 'Grand Complications MInute Repeater, World Time',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Patek Philippe',
        gender: 'Male',
        size: 40,
        material: 'White Gold',
        price: 1247000,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 25,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690654765/C4/Patek/Grand_Complications_Minute_Repeater_Tourbillon_Retrograde_Perpetual_Calendar_xgufbu.png',
        productName: 'Grand Complications Minute Repeater, Retrograde Perpetual',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Patek Philippe',
        gender: 'Male',
        size: 40,
        material: 'White Gold',
        price: 1934000,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 26,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690655067/C4/Patek/Grand_Complications_Grandmaster_Chime_Haute_Joaillerie_ymoja0.png',
        productName: 'Grand Complications Grandmaster Chime Haute Joaillerie',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Patek Philippe',
        gender: 'Male',
        size: 42,
        material: 'White Gold',
        price: 8947000,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 27,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690655283/C4/Patek/Grand_Complications_Grandmaster_Chime_j8r4sd.png',
        productName: 'Grand Complications Grandmaster Chime',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Patek Philippe',
        gender: 'Male',
        size: 42,
        material: 'Rose Gold',
        price: 6047000,
        onDiscount: 'Yes',
        oldPrice: 6147000,
    },
    {
        id: 28,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690655414/C4/Patek/Aquanaut_Luce_nkhw7r.png',
        productName: 'Aquanaut Luce',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Patek Philippe',
        gender: 'Male',
        size: 40,
        material: 'Rose Gold',
        price: 47000,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 29,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690655703/C4/Patek/Aquanaut_Flyback_Chronograph_fa4d7k.png',
        productName: 'Aquanaut Flyback Chronograph',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Patek Philippe',
        gender: 'Male',
        size: 40,
        material: 'Rose Gold',
        price: 49000,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 30,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690655960/C4/Patek/Calatrava_Ladies_Joaillerie_klbxia.png',
        productName: 'Calatrava Ladies Joaillerie',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Patek Philippe',
        gender: 'Female',
        size: 30,
        material: 'Rose Gold',
        price: 65000,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 31,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690656212/C4/Patek/Gondolo_v9zy5s.png',
        productName: 'Gondolo',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Patek Philippe',
        gender: 'Female',
        size: 30,
        material: 'Rose Gold',
        price: 447000,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 32,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690831041/C4/Jacob%20and%20Co/Epic_X_Heart_of_CR7_Baguette_kau8rw.png',
        productName: 'Epic X Heart of CR7 Baguette',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Jacob & Co',
        gender: 'Male',
        size: 40,
        material: 'Stainless Steel',
        price: 260000,
        onDiscount: 'No',
        oldPrice: null,
    },
    {
        id: 33,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690831252/C4/Jacob%20and%20Co/Twin_Turbo_Furious_Sapphire_Crystal_mtpsfd.png',
        productName: 'Twin Turbo Furious Sapphire Crystal',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Jacob & Co',
        gender: 'Male',
        size: 41,
        material: 'Stainless Steel',
        price: 2047000,
        onDiscount: 'Yes',
        oldPrice: 2447000,
    }, {
        id: 34,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690831386/C4/Jacob%20and%20Co/Twin_Turbo_jxvh0a.png',
        productName: 'Twin Turbo',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Jacob & Co',
        gender: 'Male',
        size: 40,
        material: 'Rose Gold',
        price: 647000,
        onDiscount: 'Yes',
        oldPrice: 747000,
    }, {
        id: 35,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690831520/C4/Jacob%20and%20Co/Epic_X_hdlaly.png',
        productName: 'Epic X',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Jacob & Co',
        gender: 'Male',
        size: 40,
        material: 'Stainless Steel',
        price: 67000,
        onDiscount: 'No',
        oldPrice: null,
    }, {
        id: 36,
        productImage: 'https://res.cloudinary.com/dcdmmuhf2/image/upload/v1690831680/C4/Jacob%20and%20Co/Astronomia_Flawless_Imperial_Dragon_veqilh.png',
        productName: 'Astronomia Flawless Imperial Dragon',
        productDescription: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        brand: 'Jacob & Co',
        gender: 'Male',
        size: 41,
        material: 'White Gold',
        price: 2447000,
        onDiscount: 'No',
        oldPrice: null,
    },
]

module.exports = watches;